{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:55:18.271Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:57:00.129Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:58:36.034Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:58:54.086Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:00.599Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:20.611Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:33.128Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:36.694Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:44.539Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T16:59:50.692Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T17:00:47.505Z"}
{"code":"ENOTFOUND","hostname":"_mongodb._tcp.322325","level":"error","message":"Mongo connection error querySrv ENOTFOUND _mongodb._tcp.322325","service":"identity-service","stack":"Error: querySrv ENOTFOUND _mongodb._tcp.322325\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-20T17:00:52.840Z"}
{"code":8000,"codeName":"AtlasError","connectionGeneration":2,"errorLabelSet":{},"errorResponse":{"code":8000,"codeName":"AtlasError","errmsg":"bad auth : authentication failed","ok":0},"level":"error","message":"Mongo connection error bad auth : authentication failed","ok":0,"service":"identity-service","stack":"MongoServerError: bad auth : authentication failed\n    at Connection.sendCommand (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connection.js:298:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Connection.command (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connection.js:326:26)\n    at async continueScramConversation (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:131:15)\n    at async executeScram (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:80:5)\n    at async ScramSHA1.auth (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\auth\\scram.js:39:16)\n    at async performInitialHandshake (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:104:13)\n    at async connect (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:24:9)","timestamp":"2025-02-20T17:05:29.670Z"}
{"_message":"User validation failed","errors":{"confirmPassword":{"kind":"required","message":"Path `confirmPassword` is required.","name":"ValidatorError","path":"confirmPassword","properties":{"message":"Path `confirmPassword` is required.","path":"confirmPassword","type":"required"}}},"level":"error","message":"User registration error User validation failed: confirmPassword: Path `confirmPassword` is required.","service":"identity-service","stack":"ValidationError: User validation failed: confirmPassword: Path `confirmPassword` is required.\n    at Document.invalidate (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongoose\\lib\\document.js:3329:32)\n    at C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongoose\\lib\\document.js:3090:17\n    at C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongoose\\lib\\schemaType.js:1407:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)","timestamp":"2025-02-20T17:20:19.434Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-20T17:21:28.709Z"}
{"0":"r","1":"e","2":"a","3":"s","4":"o","5":"n","6":":","level":"error","message":"Unhandled Rejection at","service":"identity-service","timestamp":"2025-02-20T17:21:50.485Z"}
{"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":"{}","service":"identity-service","timestamp":"2025-02-20T17:26:34.747Z"}
{"level":"error","message":"User registration error crypto.randomBytes is not a function","service":"identity-service","stack":"TypeError: crypto.randomBytes is not a function\n    at generateTokens (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\src\\utils\\generateToken.js:13:31)\n    at registerUser (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\src\\controllers\\identity-controller.js:39:49)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-02-20T17:30:07.770Z"}
{"level":"error","message":"User registration error RefreshToken is not defined","service":"identity-service","stack":"ReferenceError: RefreshToken is not defined\n    at generateTokens (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\src\\utils\\generateToken.js:18:3)\n    at registerUser (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\src\\controllers\\identity-controller.js:39:49)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-02-20T17:33:36.226Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-20T17:35:28.931Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T16:08:57.264Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T16:54:21.572Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T16:55:52.805Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T16:56:31.623Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T17:08:53.562Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-02-24T17:12:21.722Z"}
{"code":"ECONNREFUSED","hostname":"_mongodb._tcp.cluster0.fgo4onc.mongodb.net","level":"error","message":"Mongo connection error querySrv ECONNREFUSED _mongodb._tcp.cluster0.fgo4onc.mongodb.net","service":"identity-service","stack":"Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.fgo4onc.mongodb.net\n    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17)","syscall":"querySrv","timestamp":"2025-02-24T18:11:58.584Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":0,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-03-10T16:34:11.477Z"}
{"beforeHandshake":false,"cause":{},"connectionGeneration":1,"errorLabelSet":{},"level":"error","message":"Mongo connection error AggregateError has an empty errors array. Please check the `cause` property for more information.","service":"identity-service","stack":"MongoNetworkError: AggregateError has an empty errors array. Please check the `cause` property for more information.\n    at TLSSocket.<anonymous> (C:\\Users\\Manu\\Desktop\\Social media microservices\\identity-services\\node_modules\\mongodb\\lib\\cmap\\connect.js:285:44)\n    at Object.onceWrapper (node:events:628:26)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","timestamp":"2025-03-10T16:34:33.051Z"}
